//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OESApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teacher
    {
        public int TeacherId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string MobileNo { get; set; }
        public string EmailId { get; set; }
        public string Gender { get; set; }
        public string Qualification { get; set; }
        public Nullable<int> SubjectId { get; set; }
        public Nullable<System.DateTime> JoiningDate { get; set; }
        public Nullable<int> Salary { get; set; }
        public Nullable<int> RoleId { get; set; }
        public string Password { get; set; }
        public Nullable<System.DateTime> Lastlogin { get; set; }
        public Nullable<int> LoginAttempts { get; set; }
    
        public virtual Subject Subject { get; set; }
        public virtual Subject Subject1 { get; set; }
        public virtual UserRole UserRole { get; set; }
        public virtual UserRole UserRole1 { get; set; }
    }
}
